version: "3.1"

services:
  php5.3_apache:
    build:
      context: ./configs/php5.3
      dockerfile: Dockerfile
    container_name: php5.3_apache
    volumes:
      - ./www:/var/www/html/
    ports:
      - 80:80
      - 443:443
    network_mode: host

  php5.6_apache:
    build:
      context: ./configs/php5.6
      dockerfile: Dockerfile
    container_name: php5.6_apache
    volumes:
      - ./www:/var/www/html/
    ports:
      - 80:80
      - 443:443
    network_mode: host

  php7.0_apache:
    build:
      context: ./configs/php7.0
      dockerfile: Dockerfile
    container_name: php7.0_apache
    volumes:
      - ./www:/var/www/html/
      - ./configs/php7.0/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./configs/php7.0/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
      - ./tmp/xdebug:/tmp/xdebug
    ports:
      - 80:80
      - 443:443
    network_mode: host
    depends_on:
      - mysql
      - phpmyadmin
      - mailpit

  php7.1_apache:
    build:
      context: ./configs/php7.1
      dockerfile: Dockerfile
    container_name: php7.1_apache
    volumes:
      - ./www:/var/www/html/
    ports:
      - 80:80
      - 443:443
    network_mode: host
    depends_on:
      - mysql
      - phpmyadmin
      - mailpit

  php7.2_apache:
    build:
      context: ./configs/php7.2
      dockerfile: Dockerfile
    container_name: php7.2_apache
    volumes:
      - ./www:/var/www/html/
      - ./configs/php7.2/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - 80:80
      - 443:443
    network_mode: host
    depends_on:
      - mysql
      - phpmyadmin
      - mailpit

  php7.3_apache:
    build:
      context: ./configs/php7.3
      dockerfile: Dockerfile
    container_name: php7.3_apache
    volumes:
      - ./www:/var/www/html/
      - ./configs/php7.3/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - 80:80
      - 443:443
    network_mode: host
    depends_on:
      - mysql
      - phpmyadmin
      - mailpit
      - adminer

  php7.4_apache:
    build:
      context: ./configs/php7.4
      dockerfile: Dockerfile
    container_name: php7.4_apache
    volumes:
      - ./www:/var/www/html/
      - ./configs/php7.4/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - 80:80
      - 443:443
    network_mode: host
    depends_on:
      - mysql
      - phpmyadmin
      - mailpit
      - adminer

  mysql:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/data/mysql57:/var/lib/mysql
      - ./db/backups:/_backups
      - ./configs/db/my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"

  mysql8:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/data/mysql8:/var/lib/mysql
      - ./db/backups:/_backups
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: always
    ports:
      - 8010:80

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080

  mailpit:
    image: axllent/mailpit
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
